services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=mysql_prod
      - DB_TEST_HOST=mysql_test
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    depends_on:
      mysql_prod:
        condition: service_healthy
      mysql_test:
        condition: service_healthy
    networks:
      - backend-network

  mysql_prod:
    image: mysql:8.0
    container_name: mysql_prod
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=laravel
    ports:
      - "3306:3306"
    volumes:
      - mysql_prod_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - backend-network

  mysql_test:
    image: mysql:8.0
    container_name: mysql_test
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=laravel_test
    ports:
      - "3307:3306"
    volumes:
      - mysql_test_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - backend-network

volumes:
  mysql_prod_data:
  mysql_test_data:

networks:
  backend-network:
    driver: bridge
